INSERT INTO priorities (level)
VALUES ('LOW') ON CONFLICT DO NOTHING;
INSERT INTO priorities (level)
VALUES ('MEDIUM') ON CONFLICT DO NOTHING;
INSERT INTO priorities (level)
VALUES ('HIGH') ON CONFLICT DO NOTHING;